# Generated by Django 4.1.7 on 2023-03-25 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='leket_DB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100, verbose_name='type')),
                ('area', models.CharField(max_length=100, verbose_name='area')),
                ('location', models.CharField(max_length=100, verbose_name='location')),
                ('amount_kg', models.FloatField(verbose_name='amount_kg')),
                ('missionID', models.FloatField(verbose_name='missionID')),
                ('farmerID', models.FloatField(verbose_name='farmerID')),
                ('date', models.DateField(verbose_name='date')),
            ],
        ),
    ]
