# Generated by Django 3.2.18 on 2023-04-09 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LeketIsraelApp', '0002_auto_20230409_0108'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
