# Generated by Django 3.2.18 on 2023-06-13 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LeketIsraelApp', '0004_users1'),
    ]

    operations = [
        migrations.CreateModel(
            name='leket_DB_new',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_of_orders', models.IntegerField(default=0, verbose_name='num_of_orders')),
                ('year', models.IntegerField(default=0, verbose_name='year')),
                ('month', models.IntegerField(default=0, verbose_name='month')),
                ('week', models.IntegerField(default=0, verbose_name='week')),
                ('area', models.CharField(max_length=100, verbose_name='area')),
                ('leket_location', models.CharField(max_length=100, verbose_name='leket_location')),
                ('type', models.CharField(max_length=100, verbose_name='type')),
                ('napa_name', models.CharField(max_length=100, verbose_name='napa_name')),
                ('aklim_area', models.CharField(max_length=100, verbose_name='aklim_area')),
                ('TMY_station', models.CharField(max_length=100, verbose_name='TMY_station')),
                ('station', models.CharField(max_length=100, verbose_name='station')),
                ('ground_temp', models.FloatField(verbose_name='ground_temp')),
                ('shmita', models.BinaryField(verbose_name='shmita')),
                ('chagim', models.BinaryField(verbose_name='chagim')),
                ('sum_amount_kg', models.FloatField(verbose_name='sum_amount_kg')),
            ],
        ),
    ]
