# Generated by Django 3.2.18 on 2023-06-13 10:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LeketIsraelApp', '0005_leket_db_new'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leket_db_new',
            name='month',
        ),
        migrations.RemoveField(
            model_name='leket_db_new',
            name='num_of_orders',
        ),
        migrations.RemoveField(
            model_name='leket_db_new',
            name='week',
        ),
        migrations.RemoveField(
            model_name='leket_db_new',
            name='year',
        ),
        migrations.AddField(
            model_name='leket_db_new',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='date'),
        ),
        migrations.AddField(
            model_name='leket_db_new',
            name='group',
            field=models.IntegerField(default=0, verbose_name='group'),
        ),
    ]
