# Generated by Django 3.2.18 on 2023-06-13 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LeketIsraelApp', '0006_auto_20230613_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leket_db_new',
            name='ground_temp',
            field=models.FloatField(default=0, verbose_name='ground_temp'),
        ),
    ]
