# Generated by Django 3.2.18 on 2023-06-13 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LeketIsraelApp', '0007_alter_leket_db_new_ground_temp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leket_db_new',
            name='ground_temp',
            field=models.FloatField(null=True, verbose_name='ground_temp'),
        ),
    ]
