# Generated by Django 3.2.18 on 2023-06-13 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LeketIsraelApp', '0009_alter_leket_db_new_ground_temp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leket_db_new',
            name='chagim',
            field=models.IntegerField(default=0, verbose_name='chagim'),
        ),
        migrations.AlterField(
            model_name='leket_db_new',
            name='shmita',
            field=models.IntegerField(default=0, verbose_name='shmita'),
        ),
    ]
