# Generated by Django 3.2.18 on 2023-06-13 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LeketIsraelApp', '0010_auto_20230613_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leket_db_new',
            name='group',
            field=models.IntegerField(null=True, verbose_name='group'),
        ),
    ]
