# Generated by Django 3.2.18 on 2023-06-13 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LeketIsraelApp', '0012_alter_leket_db_new_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='leket_db_new',
            name='missionID',
            field=models.CharField(max_length=100, null=True, verbose_name='missionID'),
        ),
    ]
