# Generated by Django 3.2.18 on 2023-06-24 20:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LeketIsraelApp', '0013_leket_db_new_missionid'),
    ]

    operations = [
        migrations.CreateModel(
            name='leket_DB_24_06',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.IntegerField(null=True, verbose_name='group')),
                ('type', models.CharField(max_length=100, verbose_name='type')),
                ('area', models.CharField(max_length=100, verbose_name='area')),
                ('leket_location', models.CharField(max_length=100, verbose_name='leket_location')),
                ('amount_kg', models.FloatField(verbose_name='amount_kg')),
                ('missionID', models.CharField(max_length=100, null=True, verbose_name='missionID')),
                ('farmerID', models.CharField(max_length=100, null=True, verbose_name='farmerID')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='date')),
                ('napa_name', models.CharField(max_length=100, verbose_name='napa_name')),
                ('aklim_area', models.CharField(max_length=100, verbose_name='aklim_area')),
                ('TMY_station', models.CharField(max_length=100, verbose_name='TMY_station')),
                ('station', models.CharField(max_length=100, verbose_name='station')),
                ('max_temp', models.FloatField(null=True, verbose_name='max_temp')),
                ('min_temp', models.FloatField(null=True, verbose_name='min_temp')),
                ('ground_temp', models.FloatField(null=True, verbose_name='ground_temp')),
                ('shmita', models.IntegerField(default=0, verbose_name='shmita')),
                ('chagim', models.IntegerField(default=0, verbose_name='chagim')),
            ],
        ),
    ]
