# Generated by Django 3.2.18 on 2023-06-24 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LeketIsraelApp', '0015_auto_20230624_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leket_db_24_06',
            name='TMY_station',
            field=models.CharField(max_length=100, null=True, verbose_name='TMY_station'),
        ),
        migrations.AlterField(
            model_name='leket_db_24_06',
            name='aklim_area',
            field=models.CharField(max_length=100, null=True, verbose_name='aklim_area'),
        ),
        migrations.AlterField(
            model_name='leket_db_24_06',
            name='station',
            field=models.CharField(max_length=100, null=True, verbose_name='station'),
        ),
    ]
