# Generated by Django 4.1.7 on 2023-07-29 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LeketIsraelApp', '0016_auto_20230624_2344'),
    ]

    operations = [
        migrations.DeleteModel(
            name='leket_DB',
        ),
        migrations.DeleteModel(
            name='leket_DB_new',
        ),
        migrations.DeleteModel(
            name='Users1',
        ),
    ]
