# Generated by Django 4.1.7 on 2023-07-29 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LeketIsraelApp', '0017_delete_leket_db_delete_leket_db_new_delete_users1'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='leket_DB_24_06',
            new_name='leket_DB',
        ),
    ]
